### ISSUE TITLE
plotting functions do not restore plotting parameters when finished

### ISSUE THREAD

**Issue by barkasn** [hms-dbmi/pagoda2#21]

**Comment by barkasn** [comment]
This has been partly resolved but but some plots without par restoration may remain.

**Comment by pkharchenko** [comment]
I am not sure this is a desired feature, actually. Is it described as a standard practice somewhere? Quite often you want to add something else to the plot, and if par was reset, it’s hard to do.

**Comment by barkasn** [comment]
Yes, R packages must not modify their environment. 

https://cran.r-project.org/doc/manuals/r-release/R-exts.html
"Ideally, the R code files should only directly assign R objects and definitely should not call functions with side effects such as require and options"

http://r-pkgs.had.co.nz/r.html
"If you modify global options() or graphics par(), save the old values and reset when you’re done"

We can always keep the par in the package and restore it if additional plotting is required
