### ISSUE TITLE
Error when installing largeVis

### ISSUE THREAD

**Issue by rgupta122** [hms-dbmi/pagoda2#28]
Probably a basic question, but I am new to installing these sorts of programs into R.

I followed the commands to install NMSLIB and the largeVis folders. Does it matter where on my computer I install these (i.e. do the directory names matter?)

When I run these commands in R, I get an error:
install.packages('devtools')
library(devtools)
install('~/Library/tmp/largeVisCustom/largeVis')

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [largeVis.so] Error 1
ERROR: compilation failed for package ‘largeVis’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/largeVis’
Error: Command failed (1)

Any ideas on how to fix?

Thanks!

**Comment by rgupta122** [comment]
Thanks. That got me a little farther towards installing!

Now when installing pagoda2 I get this error:

In file included from RcppExports.cpp:4:
./../inst/include/pagoda2.h:14:10: fatal error: 'space.h' file not found
#include "space.h"
         ^~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2’
Installation failed: Command failed (1)

**Comment by pkharchenko** [comment]
That error means that it can't find nmslib headers. 
Please make sure to follow the nmslib installation step, and also don't forget to change the NMSLIB_PATH to the appropriate location on your system in this next step below:
# Specify the location where nms lib was installed in a NMSLIB_PATH environment variable
Sys.setenv("NMSLIB_PATH"="/path/to/nmslib-1.6/")

**Comment by molivarina** [comment]
Hi Peter,

I get exactly the same error when installing Pagoda2 on my Mac, despite having specified the location where nms lib is...

* installing *source* package ‘pagoda2’ ...
** libs
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -I"~/lib/nmslib/nmslib-1.6/similarity_search/include" -I"../inst/include" -I"~/lib/nmslib/nmslib-1.6/similarity_search/lshkit/include" -fopenmp -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
./../inst/include/pagoda2.h:14:10: fatal error: 'space.h' file not found
#include "space.h"
         ^~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2’




And there is a 'space.h' file in ~/lib/nmslib/nmslib-1.6/similarity_search/include/ ....

Any idea on how to fix this ?

Many thanks

**Comment by barkasn** [comment]
Hi molivarina,

The error ‘space.h’ not found is certainly an issue with the file not being in the includes file path. I don’t completely understand the text you have copy-pasted below, you have some text crossed out and it’s not clear what this refers to. I think you problem is that you  have the wrong path. If you look carefully you will see that you have specified:

/lib/nmslib/nmslib-1.6/similarity_search/lshkit/include

but in your comments you say that the library is in

~/lib/nmslib/nmslib-1.6/similarity_search/lshkit/include

Incidentally the ‘~’ doesn’t always get replaced properly in this context. Try ${HOME} or better specify an absolute path starting with ‘/’. Please let me know if you continue to have problems after amending this.

Best wishes,

Nikolas Barkas

**Comment by molivarina** [comment]
Thanks Nikolas!

Indeed, problem was solved by using ${HOME}.... However I encountered another problem. At the end, I got this error message:

** testing if installed package can be loaded
Error: package or namespace load failed for ‘pagoda2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so, 6): Symbol not found: __ZN6lshkit14GammaDoubleMLEEdd
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so
Error: loading failed
Execution halted
ERROR: loading failed

Also got lots of warning during installation

Thanks for your help!

Best,
Marina

**Comment by barkasn** [comment]
That’s a linking error at runtime, the nmslib dynamic library is not loaded or compiled properly. Check your nmslib compilation step and that you have the –L flags set correctly. If that doesn’t work try adding the location the nmslib.so file (the dynamic lib) to LD_PATH.

If you can’t resolve this, please send the full output of the nmslib compilation and of   pagoda2 compilation as individual files.

BW,

N

**Comment by barkasn** [comment]
This was an error pertaining to the particular installation of the user. It was resolved by repeating installation of R after installing fortran for mac.
