### ISSUE TITLE
garbled text

### ISSUE THREAD

**Issue by slowkow** [hms-dbmi/pagoda2#3]
I double-clicked on an aspect to view the GO terms associated with it.

The text in the "Gene sets in Aspect" window became garbled, and it stayed that way even as I clicked on other things:

<img width="545" alt="development_pagoda_application" src="https://cloud.githubusercontent.com/assets/209714/26680058/ca991692-46a5-11e7-885b-ec5d1def54d9.png">

Notably, the first 3 terms become un-clickable. This includes 004058, 0005770, 0002685. The 4th term is clickable.

Unfortunately, I can't give you detailed instructions to reproduce this error. If I find a way to reproduce it reliably, I'll update this issue.

**Comment by barkasn** [comment]
closed as non-reproducible
