### ISSUE TITLE
Error when installing pagoda2

### ISSUE THREAD

**Issue by KatjaHebestreit** [hms-dbmi/pagoda2#31]
Hi,

I went through the installation process (on a Mac) successfully until I got an error at the very end: 

install_github("hms-dbmi/pagoda2") gives the following error:

In file included from RcppExports.cpp:4:
./../inst/include/pagoda2.h:14:10: fatal error: 'space.h' file not found
#include "space.h"
         ^~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘pagoda2’

This may be a bug? I would very much appreciate your help.
Thanks so much,
Katja

**Comment by barkasn** [comment]
Hi Katja,

The issue is because the nmslib header files can't be found. Can you please check that you have set the NMSLIB_PATH variable correctly? Note that you need to provide a full path or use ${HOME} instead of '~' in that path.

Please let me know if the issue persists.

BW,

Nikolas

**Comment by KatjaHebestreit** [comment]
Hi Nikolas,

The '~' in my path was the issue. 

Thanks so much for your help! I really appreciate it.
-Katja
