### ISSUE TITLE
Differential expression results

### ISSUE THREAD

**Issue by KatjaHebestreit** [hms-dbmi/pagoda2#32]
Hi,

Congratulations to this great package! I am very impressed about how fast it is.

For the differential expression analysis using "getDifferentialGenes": What are the methods for this (did you use scde?), and could you explain me what the columns of the result output mean: "Z", "M", "highest", and "fe"?

Thank you very much,
Katja

**Comment by pkharchenko** [comment]
Hi Katja. 
The getDifferentialGenes doesn't use scde model, but uses Wilcoxon rank sum test on normalized expression values instead. This was mostly done in the interest of speed.
 I've added docs for the data frame columns into the devel branch (https://github.com/hms-dbmi/pagoda2/commit/1581bd2a938745171b6088a1a19c9f4c5e72605a). Here's the explanation for the return value:
+    ##' @return a list, with each element of the list corresponding to a cell group in the provided/used factor (i.e. factor levels); Each element of a list is a data frame listing the differentially epxressed genes (row names), with the following columns: Z - adjusted Z score, with positive values indicating higher expression in a given group compare to the rest; M - log2 fold change; highest- a boolean flag indicating whether the expression of a given gene in a given vcell group was on average higher than in every other cell group; fe - fraction of cells in a given group having non-zero expression level of a given gene;

**Comment by KatjaHebestreit** [comment]
Thanks so much, Peter!
-Katja
