### ISSUE TITLE
Pagoda 2 Quick Walkthrough

### ISSUE THREAD

**Issue by Mangos123** [hms-dbmi/pagoda2#34]
When I try to run basicP2proc() on my sparse matrix from 10X data, I get an error message: 

Error in irlba(x, nv = nPcs, nu = 0, center = cm, right_only = FALSE,  : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Any thoughts on resolving this issue? Thanks!!

**Comment by barkasn** [comment]
Hi Mangos123,

This is usually the result of low numbers of cells. How many cells are there in your sample?

basicP2proc() is a wrapper function around the standard pagoda2 steps. I would suggest that you try these steps manually one by one if you are experiencing problems. You can see the function definition here: https://github.com/hms-dbmi/pagoda2/blob/master/R/pipelineHelpers.R copied below. Your error comes from the p2$calculatePcaReduction() step. Try decreasing the number of components (nPcs) you are requesting and see if this resolves the issue. Please let me know if you continue to experience problems with this.

BW,

Nikolas

---------------------

  require(Matrix)

  p2 <- Pagoda2$new(cd, n.cores = n.cores, batch = batch);
  p2$adjustVariance(plot=F, gam.k=10);
  p2$calculatePcaReduction(nPcs = 300, n.odgenes = 3.e3, maxit = 1000)
  p2$makeKnnGraph(k = 30, type='PCA', center=TRUE, weight.type = 'none', n.cores = n.cores, distance = 'cosine')
  p2$getKnnClusters(method = infomap.community, type = 'PCA' ,name = 'infomap')
  p2$getKnnClusters(method = multilevel.community, type = 'PCA', name = 'multilevel');
  p2$getKnnClusters(method = walktrap.community, type = 'PCA', name = 'walktrap');

  M <- 30
  p2$getEmbedding(type = 'PCA', embeddingType = 'largeVis', M = M, perplexity = 30, gamma = 1/ M, alpha =1)
  p2$getEmbedding(type = 'PCA', embeddingType = 'tSNE', perplexity = 50);

**Comment by barkasn** [comment]
Hi Mangos123,

Where you able to resolve this problem?

BW,

Nikolas
