### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by zhengrongbin** [hms-dbmi/pagoda2#37]
Hi, I have this problem at the final step of installation. Do you know any solutions? I list the final part of the log information. Thanks a lot.
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘pagoda2’ in dyn.load(file, DLLpath = DLLpath, ...):
cannot load the shared object ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so, 6): Library not loaded: libboost_filesystem.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2/libs/pagoda2.so
  Reason: image not found

Does this the problem on the version of the dependance?

**Comment by barkasn** [comment]
I assume you were trying to install the devel branch?

It should be fixed in the latest devel commit 1519174

Please let me know if you continue to have problems.

BW,

Nikolas
