### ISSUE TITLE
sorted dendrograms

### ISSUE THREAD

**Issue by slowkow** [hms-dbmi/pagoda2#4]
You might consider sorting the dendrograms in the display. By default, the tree branches returned by `hclust` are not sorted by similarity.

After sorting with `dendsort::dendsort()`, the most similar branches are shown on the left and the most distant branches are shown on the right.

## Example

Here's an example of the default unsorted tree:

```r
mat_cluster_cols <- hclust(dist(t(mat)))

plot(mat_cluster_cols, main = "Unsorted Dendrogram", xlab = "", sub = "")
```

![image](https://cloud.githubusercontent.com/assets/209714/26680267/bd895d94-46a6-11e7-84a4-deb690eb9631.png)

And the sorted one:

```r
# install.packages("dendsort")
library(dendsort)

sort_hclust <- function(...) as.hclust(dendsort(as.dendrogram(...)))

mat_cluster_cols <- hclust(dist(t(mat)))

mat_cluster_cols <- sort_hclust(mat_cluster_cols)

plot(mat_cluster_cols, main = "Sorted Dendrogram", xlab = "", sub = "")
```

![image](https://cloud.githubusercontent.com/assets/209714/26680271/c19e859e-46a6-11e7-9ad3-a4c02bb88c9f.png)

**Comment by Simontuk** [comment]
The creation of the dendrogram in the web app is done in two steps. 
I included two new options for the creation of apps: innerOrder and orderDend

- innerOrder: changes the way the cells inside of each of the groups provided in "dendrogramCellGroups" are ordered. Different options possible. 

  - Can be one of "odPCA", "reductdist", "graphbased" or "knn". Currently defaults to NULL (random order inside the clusters)
- orderDend: sorts the top level dendrogram with dendsort(), but as the dendrogram is based on rather simple distances between the clusters this does not change a lot. 

They can be found in the branch _cellordering_.
