### ISSUE TITLE
error when installing pagoda2

### ISSUE THREAD

**Issue by lynhsiong** [hms-dbmi/pagoda2#45]
when I install pagoda2 in Mac OS (version 10.13.4), R reports an error when compiling:
> devtools::install_github('hms-dbmi/pagoda2', build_vignettes = FALSE)

/usr/local/clang4/bin/clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/clang4/lib -o pagoda2.so RcppExports.o binaryExport.o checkfunctions.o edgeweights.o gradients.o largeVis.o misc2.o n2knn.o pagoda1_liftover.o rank.o -L/usr/lib/ -L. -lpthread -lboost_filesystem -lboost_system -lstdc++ -ln2 -lgsl -lgslcblas -lm -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -fopenmp -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgsl
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [pagoda2.so] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2’
Installation failed: Command failed (1)

**Comment by pkharchenko** [comment]
Looks like you're missing libgsl on your system.

-peter.

**Comment by lynhsiong** [comment]
Thanks, Peter, you are right!
