### ISSUE TITLE
installing error for pagoda 

### ISSUE THREAD

**Issue by kawairine** [hms-dbmi/pagoda2#46]
Hi, 

## **First I could not installed cairo in R,** 
> install.packages("Cairo")
trying URL 'http://cran.rstudio.com/src/contrib/Cairo_1.5-9.tar.gz'
Content type 'application/x-gzip' length 86982 bytes (84 KB)
==================================================
downloaded 84 KB

* installing *source* package ‘Cairo’ ...
** package ‘Cairo’ successfully unpacked and MD5 sums checked
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... x86_64-conda_cos6-linux-gnu-cc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for pkg-config... /usr/bin/pkg-config
checking whether pkg-config knows about cairo... no
configure: CAIRO_LIBS is unset, attempting to guess it.
configure: CAIRO_CFLAGS=
checking if R was compiled with the RConn patch... no
checking cairo.h usability... no
checking cairo.h presence... no
checking for cairo.h... no
configure: error: Cannot find cairo.h! Please install cairo (http://www.cairographics.org/) and/or set CAIRO_CFLAGS/LIBS correspondingly.
ERROR: configuration failed for package ‘Cairo’
* removing ‘/home/kawai/anaconda3/lib/R/library/Cairo’
Warning in install.packages :
  installation of package ‘Cairo’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpmgtj6z/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

**# so I installed with conda instead:** 
conda install -c r r-cairo 
(Then I have cairo in R) 

And then it gave me a fatal error when I install pagoda2

install_github("hms-dbmi/pagoda2")
Downloading GitHub repo hms-dbmi/pagoda2@master
from URL https://api.github.com/repos/hms-dbmi/pagoda2/zipball/master
Installing pagoda2
'/home/kawai/anaconda3/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpmgtj6z/devtools30e2532c50dc/hms-dbmi-pagoda2-b991a6d'  \
  --library='/home/kawai/anaconda3/lib/R/library' --install-tests 

* installing *source* package ‘pagoda2’ ...
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I/home/kawai/anaconda3/lib/R/include -DNDEBUG  -I"/home/kawai/anaconda3/lib/R/library/Rcpp/include" -I"/home/kawai/anaconda3/lib/R/library/RcppArmadillo/include" -I"/home/kawai/anaconda3/lib/R/library/RcppProgress/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I/home/kawai/anaconda3/include  -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/kawai/anaconda3/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
../inst/include/pagoda2.h:14:10: fatal error: boost/progress.hpp: No such file or directory
 #include <boost/progress.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘pagoda2’
* removing ‘/home/kawai/anaconda3/lib/R/library/pagoda2’
Installation failed: Command failed (1)

It will be highly appreciated if you could inform me how I can solve this. 

Thank you!

**Comment by barkasn** [comment]
Hi kawairine,

Have you been able to resolve this problem?

BW,

Nikolas

**Comment by kawairine** [comment]
Hi Nikolas,

Thank you for checking with me and sorry for not responding, I haven't had
a chance to try it yet, because the server was down. And unfortunately, I
need to use conda because I share the cluster with other people in the
department. But I will inform you when there is a problem again.


Regards,
Kawai
