### ISSUE TITLE
p2.make.pagoda1.app assumes fastcluster is installed

### ISSUE THREAD

**Issue by erikor** [hms-dbmi/pagoda2#47]
Running through the walkthrough I encountered warnings with `p2.make.pagoda1.app` when generating the app (which then caused running the app to fail)

```
Warning message:
  6 function calls resulted in an error
```

I traced the issue back to line 62 of p1app4p2.r:

```
        hcc <- fastcluster::hclust(dd, method = "ward.D")
```
I did not have this package installed (although it is in the "Suggests" list of DESCRIPTION).  Installing the package resolved this problem.

I notice elsewhere this is handled thusly:

```
  if(is.element("fastcluster", installed.packages()[, 1])) {
    y <- fastcluster::hclust(cc, method = cluster.method)
  } else {
    y <- stats::hclust(cc, method = cluster.method)
  }
```
Should this strategy be used for `p2.make.pagoda1.app` as well?

**Comment by pkharchenko** [comment]
Good catch! Will patch.
Thanks,
-peter.

**Comment by barkasn** [comment]
fastcluster is now under the package 'Suggests'. Closing the issue

**Comment by erikor** [comment]
@barkasn but that does not fix it, does it?  If fastcluster is not installed (as it might not be since fastcluster is only in Suggests), `p2.make.pagoda1.app` will fail.  Thus it should either be in 'Imports', or the code should be something like:

```
if(is.element("fastcluster", installed.packages()[, 1])) {
    hcc <- fastcluster::hclust(dd, method = "ward.D")
  } else {
    hcc <- stats::hclust(dd, method = "ward.D")
  }
```

**Comment by barkasn** [comment]
I've moved into to imports now
