### ISSUE TITLE
Clang error during installation

### ISSUE THREAD

**Issue by elimereu** [hms-dbmi/pagoda2#53]
Hi, 

I really would like to use pagoda2 but I have a problem during the installation process.
I followed all the steps described in the github installation page but still something is not working. 
My computer is a Mac OS El Capitan v.10.11.6 and after I run the last command  install_github("hms-dbmi/pagoda2") on R I got this error: 
clang: error: unsupported option '-fopenmp'
make[1]: *** [base.o] Error 1
make: *** [sublibraries] Error 1
ERROR: compilation failed for package 'pagoda2'
* removing '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/pagoda2'

Can you help me to solve this problem?

Thank you in advance.
Bests, 

Elisabetta

**Comment by DRLaks** [comment]
Can someone fork the installation files and add the necessary script changes to those files so that anyone can install pagoda 2 with the fork?

**Comment by DRLaks** [comment]
I made a fork that worked at DRLaks/pagoda2. Just use: 
library (devtools)
install_github("DRLaks/pagoda2")
