### ISSUE TITLE
genes lost converting to pagoda2 object

### ISSUE THREAD

**Issue by ONeillMB1** [hms-dbmi/pagoda2#61]
When I convert my count matrix to a pagoda object I loose 4359 genes and I am wondering why?

```
dim(counts)
1] 13509  2069

p <- Pagoda2$new(counts,log.scale=FALSE)
dim(p$counts)
[1] 2069 9150
```

**Comment by VPetukhov** [comment]
Pagoda 2 has constructor parameter `min.cells.per.gene=30`, which filters genes, that are presented in very low number of cells. You can set it to 0 to disable this filtration.
