### ISSUE TITLE
External databases for overdispersion analysis

### ISSUE THREAD

**Issue by PavelnZ** [hms-dbmi/pagoda2#66]
Hello,
I just started using Pagoda2 and find it very helpful in single cell gene analysis. I was wondering if the algorithm supports other pathways database usage for overdispersion analysis, like Broad institute MsigDB database or custom made ones? 
Thank you,
Pavel

**Comment by barkasn** [comment]
Hi Pavel,

This is not supported currently, however there is no reason why you shouldn't be able to do it. Have a look at the p2.generate.mouse.go() function in the pipelineHelpers.R file for an example of the datastructure that would be required to run over-dispersion analysis with MSigDB.

Best wishes,

Nikolas
