### ISSUE TITLE
object 'multilevel.community' not found

### ISSUE THREAD

**Issue by x811zou** [hms-dbmi/pagoda2#69]
Hi! I am having problems in getKnnClusters function. And I could not find similar issue online.
I was following the tutorial of scRNA-data analysis pipeline using my data. Not sure what causes this problem. Could anyone help me with this?

> r$getKnnClusters(method = multilevel.community,type='PCA',name='multilevel');
Error in r$getKnnClusters(method = multilevel.community, type = "PCA",  : 
  object 'multilevel.community' not found

**Comment by x811zou** [comment]
Found solution.

**Comment by tiagobrc** [comment]
Could you please share with us your solution?

Thanks.

**Comment by pkharchenko** [comment]
You need to load the igraph library first, or specify igraph::multilevel.community explicitly.

-peter.
