### ISSUE TITLE
installing error for pagoda2  boost

### ISSUE THREAD

**Issue by ShuangHe33** [hms-dbmi/pagoda2#70]
Hi,I tried to install pagoda2, but I got the error:
> install_github("hms-dbmi/pagoda2")
Downloading GitHub repo hms-dbmi/pagoda2@master
Skipping 3 packages not available: AnnotationDbi, BiocGenerics, GO.db
√  checking for file 'C:\Users\shuan\AppData\Local\Temp\RtmpcvBPSY\remotes48fc174b6f8e\hms-dbmi-pagoda2-32676b2/DESCRIPTION'
-  preparing 'pagoda2': (970ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (418ms)
-  checking for empty or unneeded directories
-  building 'pagoda2_0.0.0.9002.tar.gz'
   
Installing package into ‘C:/Users/shuan/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'pagoda2' ...
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
../inst/include/pagoda2.h:14:30: fatal error: boost/progress.hpp: No such file or directory
 #include <boost/progress.hpp>
                              ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: RcppExports.o] Error 1
ERROR: compilation failed for package 'pagoda2'
* removing 'C:/Users/shuan/Documents/R/win-library/3.5/pagoda2'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/shuan/AppData/Local/Temp/RtmpcvBPSY/file48fc760b764e/pagoda2_0.0.0.9002.tar.gz’ had non-zero exit status

It seems that it can't find the boost path,  and my boost path is F:/boost_1_68_0， and after I add F:/boost_1_68_0 to the env, I still got the error.

Thank you in advance!

**Comment by ShuangHe33** [comment]
I paste the boost directory into R include directory, and came the new error.
> install_github("hms-dbmi/pagoda2")
Downloading GitHub repo hms-dbmi/pagoda2@master
Skipping 3 packages not available: AnnotationDbi, BiocGenerics, GO.db
√  checking for file 'C:\Users\shuan\AppData\Local\Temp\RtmpcvBPSY\remotes48fc66ac21cd\hms-dbmi-pagoda2-32676b2/DESCRIPTION' ...
-  preparing 'pagoda2': (841ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (430ms)
-  checking for empty or unneeded directories
-  building 'pagoda2_0.0.0.9002.tar.gz'
   
Installing package into ‘C:/Users/shuan/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'pagoda2' ...
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c binaryExport.cpp -o binaryExport.o
binaryExport.cpp: In function 'void WriteListToBinary(Rcpp::List, std::string, bool)':
binaryExport.cpp:198:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int embedIndex = 0; embedIndex != embedList.size(); ++embedIndex)
                                         ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c checkfunctions.cpp -o checkfunctions.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c edgeweights.cpp -o edgeweights.o
edgeweights.cpp: In member function 'arma::sp_mat ReferenceEdges::getWIJ()':
edgeweights.cpp:137:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (edgeidxtype i = 0; i < edge_from.size(); i++) {
                               ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c gradients.cpp -o gradients.o
gradients.cpp: In member function 'distancetype Gradient::distAndVector(const coordinatetype*, const coordinatetype*, coordinatetype*) const':
gradients.cpp:18:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int d = 0; d < D; d++) {
                    ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c largeVis.cpp -o largeVis.o
largeVis.cpp: In constructor 'MomentumVisualizer::MomentumVisualizer(vertexidxtype*, vertexidxtype*, coordinatetype*, const dimidxtype&, const vertexidxtype&, const edgeidxtype&, distancetype, const iterationtype&, const float&, const unsigned int&, const double&, const double&)':
largeVis.cpp:164:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (vertexidxtype i = 0; i != D*N; ++i) momentumarray[i] = 0;
                               ^
largeVis.cpp: In function 'arma::mat sgd(arma::mat&, arma::ivec&, arma::ivec&, arma::ivec&, arma::vec&, const double&, const double&, const uword&, const int&, const double&, Rcpp::Nullable<Rcpp::Vector<14, Rcpp::PreserveStorage> >, const bool&, Rcpp::Nullable<Rcpp::Vector<14, Rcpp::PreserveStorage> >, Rcpp::Nullable<Rcpp::Vector<14, Rcpp::PreserveStorage> >, bool)':
largeVis.cpp:254:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (edgeidxtype e = 0; e < targets_i.n_elem; ++e) negweights[targets_i[e]]++;
                             ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c misc2.cpp -o misc2.o
misc2.cpp: In function 'int non0LogColLmS(SEXP, const mat&, const vec&, int, int)':
misc2.cpp:20:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int g=1;g<p.size();g++) {
                        ^
misc2.cpp: In function 'Rcpp::DataFrame colMeanVarS(SEXP, SEXP, int)':
misc2.cpp:56:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int j=0;j<rs.size();j++) { if(rs[j]) { nrows++; } }
                  ^
misc2.cpp: In function 'arma::mat colSumByFac(SEXP, SEXP)':
misc2.cpp:106:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int j=0;j<rs.size();j++) { 
                ^
misc2.cpp: In function 'arma::mat jsDist(const mat&)':
misc2.cpp:220:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0;i<(m.n_cols-1);i++) {
                ^
misc2.cpp:222:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int j=i+1;j<m.n_cols;j++) {
                    ^
misc2.cpp: In function 'arma::ivec orderColumnRows(const ivec&, arma::ivec&)':
misc2.cpp:241:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int j=0;j<(p.n_elem-1);j++) {
                ^
misc2.cpp: In function 'arma::vec smatColVecCorr(SEXP, SEXP, bool)':
misc2.cpp:261:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if(v.size()!=dims[0]) { stop("smatColVecCorr(): vector must be the same length as the number of rows in the matrix!"); }
              ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c n2knn.cpp -o n2knn.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c pagoda1_liftover.cpp -o pagoda1_liftover.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -I"../inst/include" -I"./n2/include" -I"./include" -fopenmp    -O2 -Wall  -mtune=generic -c rank.cpp -o rank.o
make[1]: Entering directory '/cygdrive/c/Users/shuan/AppData/Local/Temp/Rtmp2PkuK0/R.INSTALL57ac2ed3619/pagoda2/src-i386/n2'
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c base.cc -o base.o
base.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c hnsw.cc -o hnsw.o
hnsw.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
hnsw.cc: In member function 'void n2::Hnsw::Build(int, int, int, int, float, n2::NeighborSelectingPolicy, n2::GraphPostProcessing, bool)':
hnsw.cc:290:10: warning: unused variable 'is_levelmult_set' [-Wunused-variable]
     bool is_levelmult_set = false;
          ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c hnsw_node.cc -o hnsw_node.o
hnsw_node.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c distance.cc -o distance.o
distance.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c heuristic.cc -o heuristic.o
heuristic.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/shuan/Documents/R/win-library/3.5/Rcpp/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppArmadillo/include" -I"C:/Users/shuan/Documents/R/win-library/3.5/RcppProgress/include"     -O3 -march=native -std=c++11 -pthread -fPIC -fopenmp -I"./include"   -O2 -Wall  -mtune=generic -c mmap.cc -o mmap.o
mmap.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright 2017 Kakao Corp. <http://www.kakaocorp.com>
 ^
mmap.cc:18:22: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
                      ^
compilation terminated.
make[1]: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:213: mmap.o] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/shuan/AppData/Local/Temp/Rtmp2PkuK0/R.INSTALL57ac2ed3619/pagoda2/src-i386/n2'
make: *** [Makevars:18: sublibraries] Error 1
ERROR: compilation failed for package 'pagoda2'
* removing 'C:/Users/shuan/Documents/R/win-library/3.5/pagoda2'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/shuan/AppData/Local/Temp/RtmpcvBPSY/file48fc2bf11/pagoda2_0.0.0.9002.tar.gz’ had non-zero exit status

**Comment by VPetukhov** [comment]
Hi @ShuangHe33 ,

Thank you for detailed log, but indeed, pagoda 2 never assumed to be built on Windows. Particularly, because [n2](https://github.com/kakao/n2) library, which we depends on, can be built only for UNIX-like systems. And it's exactly issue you've met: "sys/mman.h" is a UNIX header.

**Comment by VPetukhov** [comment]
I added this information to README in 3ee3a17
