### ISSUE TITLE
extracting the normalized count matrix

### ISSUE THREAD

**Issue by sroyyors** [hms-dbmi/pagoda2#75]
Hi,
I am interested to get the normalized count matrix after calling adjustVariance. Let's say p is the pagoda2 object. After calling p$adjustVariance, is the normalized count matrix in p$count or somewhere else?
thanks,
Sushmita

**Comment by VPetukhov** [comment]
Hi,
Pagoda doesn't store normalized matrix explicitly. Instead you can get variance scaling factor for each gene from `p2_object$misc$varinfo$gsf` and multiply `p2_object$counts` by this factors.

**Comment by sroyyors** [comment]
great, thank you. And the $counts is just depth normalized?

**Comment by VPetukhov** [comment]
Yes
