### ISSUE TITLE
Creating a single pagoda2 object from multiple count matrices

### ISSUE THREAD

**Issue by kiter2520** [hms-dbmi/pagoda2#76]
I have datasets of the same cell type from four different treatment conditions and I'm wondering if there's a way I can combine these count matrices into a single pagoda2 object so that I can visualize the differences between the four. Can't seem to find any documentation on a feature like this. Such a function would be analogous to Seurat's MergeSeurat function.

**Comment by VPetukhov** [comment]
First solution is just to combine matrices for these datasets before running Pagoda. You can use this code:
```R

ExtendMatrix <- function(mtx, col.names) {
  new.names <- setdiff(col.names, colnames(mtx))
  ext.mtx <- matrix(0, nrow=nrow(mtx), ncol=length(new.names))
  colnames(ext.mtx) <- new.names
  return(cbind(mtx, ext.mtx)[,col.names])
}

MergeCountMatrices <- function(cms) {
  cms <- lapply(cms, Matrix::t)
  gene.union <- lapply(cms, colnames) %>% Reduce(union, .)

  res <- lapply(cms, ExtendMatrix, gene.union) %>% Reduce(rbind, .)
  return(Matrix::t(res))
}

cm_merged <- MergeCountMatrices(count_matrices)
```

Second, if you want to combine these datasets accounting for batch effect, you may consider [Conos](https://github.com/hms-dbmi/conos) tool for dataset alignment.

**Comment by kiter2520** [comment]
Thanks, Viktor! I'll try out conos
