### ISSUE TITLE
dgCMatrix vs. dgTMatrix

### ISSUE THREAD

**Issue by JEFworks** [hms-dbmi/pagoda2#8]
`PAGODA2` uses slotNames unique to `dgCMatrix` class objects ex. `p`. Coercion into sparse matrices can also produce `dgTMatrix` objects it seems, which when passed to `PAGODA` causes errors. It would be good to check and reclass as needed within `Pagoda2$new()`

**Comment by barkasn** [comment]
fixed in devel branch
