### ISSUE TITLE
Nothing happens after install_github("hms-dbmi/pagoda2")

### ISSUE THREAD

**Issue by kaizen89** [hms-dbmi/pagoda2#89]
I am using R 3.6.1 on ubuntu. When I rung `devtools::install_github("hms-dbmi/pagoda2")` nothing happens, it says `Downloading GitHub repo hms-dbmi/pagoda2@master` and then nothing happens. I also tried `devtools::install`
Any suggestion?

**Comment by VPetukhov** [comment]
I've met such problems with other packages. Don't know exact reason, maybe some server network configuration. An easy way to bypass it is to download the package by hands (`git clone https://github.com/hms-dbmi/pagoda2.git`) and then installing it from a local folder (`devtools::install("pati/to/folder")`). Or did you mean that by "I also tried `devtools::install`"? If so, what was the output?

**Comment by kaizen89** [comment]
Yes, that's what I meant with `devtools::install`. But actually after another trial and with updating some of the dependencies, I was able to install it. Thanks
