### ISSUE TITLE
2 levels in p2.metadata.from.factor

### ISSUE THREAD

**Issue by Simontuk** [hms-dbmi/pagoda2#9]
If you use p2.metadata.from.factor with a factor with 2 levels it results in a object with the same color for both classes:

`
fact <- as.factor(c(1,2));  
names(fact) <- c("A","B");  
test <- p2.metadata.from.factor(fact,displayname="test");
test
`
-->
$palette
"#FF0000FF" "#FF0000FF"

**Comment by barkasn** [comment]
fixed in devel

**Comment by pkharchenko** [comment]
Related to this, please document how to make metadata somewhere. The helper functions don’t cover all the cases (like making metadata with specific colors). 
Thanks,
-peter.

**Comment by barkasn** [comment]
There was an example in the https://github.com/hms-dbmi/pagoda2/blob/master/vignettes/pagoda2.Rmd which I have now added to the function documentation (on devel). ?p2.metadata.from.factor will bring it up.
