### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xuebaliang** [hms-dbmi/pagoda2#90]
hello, recently I failed to install the pagoda2 on my linux server. The problem occured in install_github. Thus can you supply it on CRAN or supply one offline version ".tar.gz"??Thanks.

**Comment by rrydbirk** [comment]
Can you provide some more details on the topic? What did you try to run, which R version are you running, what error did you receive, etc.

You can download and build from GitHub everything else fails:
https://stackoverflow.com/questions/2751227/how-to-download-source-in-zip-format-from-github

**Comment by VPetukhov** [comment]
@xuebaliang , one reason could be an outdated devtools package. Please ensure that it's above v2.0.

> Thus can you supply it on CRAN

That's quite unlikely.

>  supply one offline version ".tar.gz"

Did you try to clone the repo and to run `devtools::install`? Should be around the same effect.

**Comment by xuebaliang** [comment]
Thanks for your reply. The main reason is that I can not connect the github well. I have fixed this problem by downloading the .zip file from the github and then installing it offine.
