### ISSUE TITLE
scanpy h5ad to pagoda2 object(s)

### ISSUE THREAD

**Issue by alejandro-jimenezsanchez** [hms-dbmi/pagoda2#91]
I have various anndatas as h5ad files from scanpy, and I would like to read in these to use conos.

However, the tutorials all start from already made pagoda2 objects (Robj).

I am not familiar with pagoda2, so I was wondering if someone could point me out the best way to create a pagoda2 object given ideally h5ad anndata files.

Thanks

**Comment by pkharchenko** [comment]
Can you get a count matrix out of these objects in R? That’s all that pagoda2 needs.

**Comment by alejandro-jimenezsanchez** [comment]
@pkharchenko thanks!

Yeah, it's possible I was getting error after error. What seems to work is the following:

Save the `scanpy` sparse_matrix object as a `dgc` object using [this](https://github.com/theislab/anndata2ri/issues/8#issuecomment-482925987) function from the `scanpy` people.

Then in `R` read and convert that matrix to `dgCMatrix` by:

```
dgc_1 <- readMM("~/dgc_1.mtx")
dgc_1 <- as(dgc_1, "dgCMatrix")
```

Assign columns (cells) and row (genes) names accordingly.

```
columns_1 <- read.csv("~/cells_1.txt", sep="\t")
rows_1 <- read.csv("~/genes_1.txt", sep="\t")

colnames(dgc_1) <- columns_1$index
colnames(dgc_2) <- columns_2$index
```

Make unique row names

```
rownames(dgc_1) <- make.unique(rownames(dgc_1))
```

I did that for 2 matrices, and made a list of them to pass them to:

```
# Preprocess matrix list
panel.preprocessed <- lapply(
	matrix_list,
	basicP2proc,
	n.cores=32, 
	min.cells.per.gene=0, 
	n.odgenes=2e3, 
    get.largevis=FALSE, make.geneknn=FALSE)
```

And it is running correctly, till that step.

Thanks again!
