### ISSUE TITLE
Error: no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by KabitaBaral1** [hms-dbmi/pagoda2#92]
Hi,
I am running scde/PAGODA and I keep running into the following error:

q_mx <- apply(q_mx,2,function(x) {storage.mode(x) <- 'integer'; x})
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
Calls: apply ... as.matrix -> as.matrix.default -> array -> as.vector

Could you please help me with how I could fix this? Thank you

Following are the packages information:
> library(tidyverse)
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.0     ✔ purrr   0.3.3
✔ tibble  2.1.3     ✔ dplyr   0.8.5
✔ tidyr   1.0.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
> library(scde)
Loading required package: flexmix
Loading required package: lattice
> library(parallel)
> library(tidyverse)
> library(flexmix)
> library(scde)
> library(methods)
> library(org.Hs.eg.db)
Loading required package: AnnotationDbi
Loading required package: stats4
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following object is masked from ‘package:flexmix’:

    unique

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: Biobase
Welcome to Bioconductor
    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.
Loading required package: IRanges
Loading required package: S4Vectors
Attaching package: ‘S4Vectors’
The following objects are masked from ‘package:dplyr’:
    first, rename
The following object is masked from ‘package:tidyr’:
    expand
The following object is masked from ‘package:base’:
    expand.grid
Attaching package: ‘IRanges’
The following objects are masked from ‘package:dplyr’:
    collapse, desc, slice
The following object is masked from ‘package:purrr’:
    reduce
Attaching package: ‘AnnotationDbi’
The following object is masked from ‘package:dplyr’:
    select

**Comment by VPetukhov** [comment]
I'm not sure how is it relevant for Pagoda2, but looks like `q_mtx` is not a matrix. Please, try to run `apply(as.matrix(q_mx),2,function(x) {storage.mode(x) <- 'integer'; x})` and if it fails, check `class(q_mtx)`
